"""entries table

Revision ID: d61fcb84234b
Revises: 1e7ecdbbeaf1
Create Date: 2024-05-28 20:32:20.421735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61fcb84234b'
down_revision = '1e7ecdbbeaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creator_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('skill_rate', sa.Integer(), nullable=False),
    sa.Column('players_rate', sa.Integer(), nullable=False),
    sa.Column('quest', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('race', sa.String(length=50), nullable=False),
    sa.Column('char_class', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_index('ix_entry_description')
        batch_op.drop_index('ix_entry_title')

    op.drop_table('entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.create_index('ix_entry_title', ['title'], unique=False)
        batch_op.create_index('ix_entry_description', ['description'], unique=False)

    op.drop_table('character')
    op.drop_table('weapon')
    op.drop_table('spell')
    op.drop_table('skill')
    op.drop_table('creator_account')
    op.drop_table('characteristic')
    # ### end Alembic commands ###
